configureExp;
imSigProcBufferErrP('epochEventType','stimulus_errp.target','freqband',freqband,...
                   'clsfr_type','ersp','trlen_ms',trlen_ms_ErrP,...
                   'calibrateOpts',calibrateOpts,'trainOpts',trainOpts,...
                   'contFeedbackOpts',contFeedbackOpts,...
                   'epochFeedbackOpts',epochFeedbackOpts,...
                   'userFeedbackTable',userFeedbackTable,...
                   'useGUI',0);
