configureExp;
imSigProcBufferErrP('epochEventType','stimulus_errp.target','freqband',freqband_errp,...
                   'clsfr_type','erp','trlen_ms',trlen_ms_ErrP,...
                   'calibrateOpts',calibrateOpts,'trainOpts',trainOpts,'timeout_ms',timeout_ms,'verb',verb);
