configureExp;
imSigProcBufferIM('epochEventType','stimulus_im.target','freqband_im',freqband_im,...
                   'clsfr_type','ersp','trlen_ms',trlen_ms_im,...
                   'calibrateOpts',calibrateOpts_im,'trainOpts',trainOpts_im,'timeout_ms',timeout_ms,'verb',verb);       