configureExp;
imSigProcBufferIM('epochEventType','stimulus_im.target','freqband_im',freqband,...
                   'clsfr_type','ersp','trlen_ms',trlen_ms,...
                   'calibrateOpts',calibrateOpts,'trainOpts',trainOpts);
               
               
